eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # =====================================
      - id: 163
        uri: http://www.163.com/
        order: 9000
        predicates:
        - Path=/163/**
      # =====================================  LoadBalancerClient Filter的使用比较简单，只需在url前加上lb
      - id: service-hi
        uri: http://localhost:8762
        order: 10000
        predicates:
        - Path=/service-hi/**
      # =====================================
#      - id: service-feign
#        uri: lb://service-feign
#        order: 10000
#        predicates:
#        - Path=/service-feign/**



server:
  port: 8800


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

feign:
  hystrix:
    enabled: true


