spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangcz3/SpringcloudConfig
          search-paths: respo
          username: huangcz3
          password: Hcz960821
      label: master
    stream:
      kafka:
        binder:
          #Kafka的服务端列表，默认localhost
          brokers: 192.168.74.11:9092
    bus:
      enabled: true



server:
  port: 8888


#http请求地址和资源文件映射如下:
#
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties

